---
title: "Simple document"
output: github_document:
---

```{r setup, include = FALSE}
library(tidyverse)
library(patchwork)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

make a scatterplot but fancy this time
```{r}
weather_df
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .3) #color here

#or 

weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + #color here
  geom_point(alpha = .3) +
  labs(
    title = "Temperature scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location",
    caption = "Weather data taken from rnoaa package for three stations."
  )
```

Sclaes -- start with `x` and `y` and then do `color`.

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + #color here
  geom_point(alpha = .3) +
  labs(
    title = "Temperature scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location",
    caption = "Weather data taken from rnoaa package for three stations."
  ) + 
  scale_x_continuous(
    breaks = c(-15,0,20),
    labels = c("-15C", "0", "20") + 
  scale_y_continuous(
    limits = c(0,30), #shows data only between 0 and 30
    transform = "sqrt")
  )
```

look at color:

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + #color here
  geom_point(alpha = .3) +
  labs(
    title = "Temperature scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location",
    caption = "Weather data taken from rnoaa package for three stations."
  ) + 
    scale_color_hue(h= c(100,400))
```

color paletted 
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + #color here
  geom_point(alpha = .3) +
  labs(
    title = "Temperature scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location",
    caption = "Weather data taken from rnoaa package for three stations."
  ) + 
  viridis::scale_color_viridis(discrete = TRUE)
```

#Themes 

```{r}
ggpscatterplot = #puts all in this dataframe for next step
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + #color here
  geom_point(alpha = .3) +
  labs(
    title = "Temperature scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location",
    caption = "Weather data taken from rnoaa package for three stations."
  ) + 
  viridis::scale_color_viridis(discrete = TRUE)
```

```{r}
ggpscatterplot =
    theme(legend.position = "bottom")
```

```{r}
ggpscatterplot = 
  theme_bw() +  #the order of these themes matter
  theme(legend.position = "bottom")
```

```{r}
ggpscatterplot = 
  theme(legend.position = "bottom") +  #the order of these themes matter
  theme_minimal()
```

```{r}
ggpscatterplot = 
  theme(legend.position = "bottom") +  #the order of these themes matter
  theme_classic()
```

```{r}
ggpscatterplot = 
  theme(legend.position = "bottom") +  #the order of these themes matter
  ggthemes::theme_excel()
```

Learning Assessment
```{r}

weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name, size = prcp)) + #color here
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) +
  labs(
    title = "Max Temp Over Time",
    x = "Date",
    y = "Maximum Temp (C)",
    color = "Location",
    caption = "Seasonal variatino in Max Temp.",
    size = "precipition") + #can add this line
  viridis::scale_color_viridis(discrete = TRUE) + 
  theme_minimal() +
  theme(legend.position = "bottom"
  )
```

Extra bonus stuff in `ggplot`
USe different datasets in different `geom`s
```{r}
central_park_df =
  weather_df |> 
  filter(name == "CentralPark_NY")

molokai_df =
  weather_df |>
  filter(name == "Molokai_HI")

molokai_df |>
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point() +
  geom_line(data = central_park_df)
```

##multiple panels

```{r}
weather_df |>
  ggplot(aes(x = tmax, fill = name)) + 
  geom_density() + 
  facet_grid(. ~ name)
```

```{r}
ggp_tmax_tmin = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3)

ggp_tmax_density =
  weather_df |> 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3)

ggp_tmax_date =
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() + 
  geom_smooth(se = FALSE)

ggp_tmax_tmin + ggp_tmax_density

(ggp_tmax_tmin + ggp_tmax_density)/ggp_tmax_date
```

default options preferred

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Data manipulation

